version: '3.9'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: na3eeman_website
    environment:
      - "${WEBSITE_PORT:-3000}:80"
    ports:
      - "${WEBSITE_PORT:-3000}:8080"
    networks:
      - website_network
    restart: unless-stopped

networks:
  website_network:
    name: na3eeman_website_network
    driver: bridge
